name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 23 * * *'  # 每天早上7点（北京时间）
    - cron: '0 10 * * *'  # 每天晚上6点（北京时间）

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10  # 使用更稳定的 Python 版本
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies with retry
      run: |
        python -m pip install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple
        pip cache purge  # 清除 pip 缓存
        for i in {1..3}; do
          pip install --no-cache-dir flake8 pytest -i https://pypi.tuna.tsinghua.edu.cn/simple && break
          echo "pip install 失败，等待 10 秒后重试..."
          sleep 10
        done
        if [ -f requirements.txt ]; then
          for i in {1..3}; do
            pip install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple && break
            echo "requirements.txt 安装失败，等待 10 秒后重试..."
            sleep 10
          done
        fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Python script with retry
      run: |
        for i in {1..3}; do  # 最多重试3次
          echo "尝试运行 main.py (第 $i 次)..."
          python main.py && break  # 成功则退出循环
          echo "执行失败，等待 10 秒后重试..."
          sleep 10
        done
